# https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard
set-option -g default-command "reattach-to-user-namespace -l bash"

# To copy/paste: # <PREFIX>-[ to enter copy mode # <Space> to select text # <Enter> to copy and exit copy mode
# <PREFIX>-] to paste

# act like vim
set-option -g status-keys vi
setw -g mode-keys vi
setw -g mode-mouse on

# look good
set -g default-terminal "screen-256color"

# use C-a as prefix (like GNU screen)
unbind C-b
set -g prefix C-a

bind a send-prefix

# use current WD for new windows
bind c new-window -c "#{pane_current_path}"

# use vim bindings to move through panes
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind-key -r C-h select-window -t :-
bind-key -r C-l select-window -t :+

# # kill
# unbind k
# bind k confirm-before "kill-window"

# reload config
unbind r
bind r last-window

unbind ^W
bind ^W split-window -p 25 '$EDITOR $(cat ~/.current-project)' \; swap-pane -D
unbind ^T
bind ^T split-window -p 25

# cycle through panes
unbind ^A
bind ^A select-pane -t :.+

unbind Right
bind Right resize-pane -R 8
unbind Left
bind Left resize-pane -L 8
unbind Up
bind Up resize-pane -U 4
unbind Down
bind Down resize-pane -D 4

# time machine
set -g history-limit 999999

# Colors in tmux statuslines work like so
# #[fg=magenta,bold]...#[default]
# Special characters in status strings:
# #H Hostname of local host
# #S Session name
# #T Current window title
# ## A literal ‘#’

# Statusbar settings

# amount of time for which status line messages and other indicators
# are displayed. time is in milliseconds.
set -g display-time 2000

set-option -g status on
set-option -g status-utf8 on

# tmux-powerline
set-option -g status-interval 2
set-option -g status-justify "centre"
set-option -g status-left-length 60
set-option -g status-right-length 90
set-option -g status-left "#(~/.tmux-powerline/powerline.sh left)"
set-option -g status-right "#(~/.tmux-powerline/powerline.sh right)"

# small screens won't hold me back
setw -g aggressive-resize on
setw -g monitor-activity on

# default statusbar colors
set-option -g status-attr default
set-option -g status-fg colour136 #yellow
set-option -g status-bg colour235 #base02

# default window title colors
setw -g window-status-attr dim
setw -g window-status-fg colour244
setw -g window-status-bg default

# active window title colors
setw -g window-status-current-fg colour166 #orange
setw -g window-status-current-bg default
setw -g window-status-current-attr bright
setw -g window-status-current-format '► #[fg=white]#I#[fg=colour123] #W#F '
setw -g window-status-format '#[fg=yellow]#I#[default] #W#F'

# pane dividers colors
setw -g pane-border-fg colour235 #base02
setw -g pane-active-border-fg colour240 #base01

# message text
set-option -g message-bg colour235 #base02
set-option -g message-fg colour166 #orange

# pane number display
set-option -g display-panes-active-colour colour33 #blue
set-option -g display-panes-colour colour166 #orange

# clock
set-window-option -g clock-mode-colour colour64 #green

# status bar configuration
# SEP='  |  '
# set-option -g status-left '⌘  #[fg=red]#S#[default]  #(whoami)@#H#[default]'$SEP

# right
# task warrior count
# tw='#[fg=green]#(bash "/Users/jenner/Source/Scripts and sorcery/tmux/tasks.sh")#[default]'

# battery status
# batt='#[fg=yellow]#(bash "/Users/jenner/Source/Scripts and sorcery/tmux/battery.sh")#[default]'

# email checker
#tm_email='#[fg=yellow]#(/usr/bin/ruby ~/.private/mail_check.rb)#[default]'

# date and such
# tm_date='#[fg=blue]#(date "+%d/%m/%Y %H:%M")#[default] '

# set-option -g status-right $batt$SEP$tw$SEP$tm_date

# set-option -g status-right-length 1000
# set-option -g status-left-length 60

